# ----------------------------------------------------------------------
# 游볭 HOME ASSISTANT MEAL PLANNER PACKAGE
# ----------------------------------------------------------------------
# Tento bal칤캜ek obsahuje konfiguraci pro pl치nov치n칤 j칤deln칤캜ku.
# Vy쬬duje vytvo콏en칠 To-Do seznamy (viz README).

# 1. DEFINICE SEZNAM콡 J칈DEL (ZDROJE)
input_select:
  # Zdrojov칠 seznamy pro v칳b캩r (pouze uk치zka 5 j칤del)
  dummy_snidane:
    name: "Sn칤dan캩 list"
    options: &seznam_snidane
      - "---"
      - "Avok치dov칳 toast + vejce"
      - "Chia k치va + jogurt"
      - "M칤chan치 vejce na cibulce"
      - "Ovesn치 ka코e s ovocem"
      - "P치rky s ho콏캜ic칤"

  dummy_obed:
    name: "Ob캩d list"
    options: &seznam_obed
      - "---"
      - "Burrito + losos"
      - "Cuketa pln캩n치 masem"
      - "Ku콏e na paprice"
      - "Sv칤캜kov치 na smetan캩"
      - "콎칤zek s bramborov칳m sal치tem"

  dummy_svacina:
    name: "Sva캜ina list"
    options: &seznam_svacina
      - "---"
      - "Jablko"
      - "Jogurt s vlo캜kami"
      - "Kef칤rov칠 ml칠ko"
      - "Oblo쬰n칳 chl칠b"
      - "Ty캜inka prote칤nov치"

  dummy_vecere:
    name: "Ve캜e콏e list"
    options: &seznam_vecere
      - "---"
      - "Avok치dov칳 toast + vejce"
      - "Burrito + losos"
      - "Gul치코ov치 pol칠vka"
      - "T캩stovinov칳 sal치t"
      - "Zeleninov칳 sal치t s tu켿치kem"

  # V칳b캩r receptu pro zobrazen칤 surovin (Frontend)
  vyber_receptu:
    name: "Vyber recept pro zobrazen칤 surovin"
    icon: mdi:chef-hat
    options:
      - "Avok치dov칳 toast + vejce"
      - "Burrito + losos"
      - "Cuketa pln캩n치 masem"
      - "Chia k치va + jogurt"
      - "Ku콏e na paprice"

  # ------------------------------------------------------------------
  # DEFINICE DN콡 (14 dn칤 - Lich칳/Sud칳 t칳den)
  # ------------------------------------------------------------------
  # T칳den 1 (Lich칳)
  menu_t1_po_snidane: { name: "Lich칳 Po Sn칤dan캩", icon: mdi:coffee, options: *seznam_snidane }
  menu_t1_po_obed:    { name: "Lich칳 Po Ob캩d", icon: mdi:food, options: *seznam_obed }
  menu_t1_po_svacina: { name: "Lich칳 Po Sva캜ina", icon: mdi:apple, options: *seznam_svacina }
  menu_t1_po_vecere:  { name: "Lich칳 Po Ve캜e콏e", icon: mdi:food-variant, options: *seznam_vecere }
  # ... (Zde by pokra캜ovaly definice pro 칔t-Ne pro T1 a T2. Pro p콏ehlednost zkr치ceno.)
  # U쬴vatel si zde mus칤 doplnit zbytek dn칤 podle vzoru v칳코e.

# 2. SENZORY (Kalorie) - Uk치zka
template:
  - sensor:
      - name: "Kalorie T1 Po Sn칤dan캩"
        unique_id: kalorie_lichy_po_snidane
        unit_of_measurement: "kcal"
        state: >
          {% set mapa = {
            "Avok치dov칳 toast + vejce": 350,
            "Chia k치va + jogurt": 250,
            "M칤chan치 vejce na cibulce": 400
          } %}
          {{ mapa.get(states('input_select.menu_t1_po_snidane'), 0) }}

# 3. SKRIPT NA GENEROV츼N칈 N츼KUPU
script:
  planovac_pridat_den_do_nakupu:
    alias: Pl치nova캜 - P콏idat den do n치kupu
    icon: mdi:cart-plus
    description: "P콏evede j칤dla z vybran칠ho dne na suroviny a p콏id치 je do n치kupn칤ch seznam콢."
    fields:
      den:
        description: Zkratka dne (po, ut...)
        example: po
      tyden:
        description: Ozna캜en칤 t칳dne (t1/t2)
        example: t1
    sequence:
      # 1. Vymaz치n칤 hotov칳ch polo쬰k ze seznam콢
      - action: todo.remove_completed_items
        target:
          entity_id:
            - todo.nakupni_seznam_pecivo
            - todo.nakupni_seznam_ovoce_a_zelenina
            - todo.nakupni_seznam_chladaky
            - todo.nakupni_seznam_maso
            - todo.nakupni_seznam_napoje
            - todo.nakupni_seznam_mrazene
            - todo.nakupni_seznam_drogerie_a_domacnost
            - todo.nakupni_seznam_ostatni
      
      # 2. Definice recept콢 a surovin
      - variables:
          recepty:
            "---": []
            "Avok치dov칳 toast + vejce":
              - Avok치do
              - Chl칠b
              - Vejce
            "Burrito + losos":
              - Tortilla
              - Losos
              - Fazole
              - Kuku콏ice
            "Cuketa pln캩n치 masem":
              - Cuketa
              - Mlet칠 maso
              - S칳r
            "Chia k치va + jogurt":
              - Chia sem칤nka
              - Jogurt b칤l칳
              - K치va
            "Ku콏e na paprice":
              - Ku콏e
              - Smetana
              - T캩stoviny
              - Paprika sladk치

          # Mapov치n칤 surovin do konkr칠tn칤ch seznam콢
          mapa_seznamu:
            Avok치do: todo.nakupni_seznam_ovoce_a_zelenina
            Cuketa: todo.nakupni_seznam_ovoce_a_zelenina
            Chl칠b: todo.nakupni_seznam_pecivo
            K치va: todo.nakupni_seznam_ostatni
            Ku콏e: todo.nakupni_seznam_maso
            Losos: todo.nakupni_seznam_maso
            Mlet칠 maso: todo.nakupni_seznam_maso
            Smetana: todo.nakupni_seznam_chladaky
            S칳r: todo.nakupni_seznam_chladaky
            Tortilla: todo.nakupni_seznam_pecivo
            Vejce: todo.nakupni_seznam_chladaky
          
          vsechny_seznamy:
            - todo.nakupni_seznam_pecivo
            - todo.nakupni_seznam_ovoce_a_zelenina
            - todo.nakupni_seznam_chladaky
            - todo.nakupni_seznam_maso
            - todo.nakupni_seznam_napoje
            - todo.nakupni_seznam_mrazene
            - todo.nakupni_seznam_drogerie_a_domacnost
            - todo.nakupni_seznam_ostatni

      # 3. Logika p콏id치n칤 (Loop)
      - repeat:
          for_each: "{{ vsechny_seznamy }}"
          sequence:
            - variables:
                aktualni_seznam: "{{ repeat.item }}"
            - action: todo.get_items
              target:
                entity_id: "{{ aktualni_seznam }}"
              response_variable: seznam
            - variables:
                vsechny_polozky: |-
                  {% set ns = namespace(items={}) %}
                  {# Na캜ten칤 st치vaj칤c칤ch polo쬰k #}
                  {% if seznam and aktualni_seznam in seznam %}
                    {% for i in seznam[aktualni_seznam]['items'] %}
                      {% set t = i.summary %}
                      {% if 'x ' in t %}
                        {% set c = t.split('x ')[0] | int(1) %}
                        {% set n = t.split('x ')[1] %}
                      {% else %}
                        {% set c = 1 %}
                        {% set n = t %}
                      {% endif %}
                      {% set ns.items = dict(ns.items, **{n: ns.items.get(n, 0) + c}) %}
                    {% endfor %}
                  {% endif %}
                  {# P콏id치n칤 nov칳ch surovin z menu #}
                  {% for chod in ['snidane','obed','svacina','vecere'] %}
                    {% set e = 'input_select.menu_' ~ tyden ~ '_' ~ den ~ '_' ~ chod %}
                    {% set jidlo = states(e) | default('---') %}
                    {% if jidlo in recepty %}
                      {% for p in recepty[jidlo] %}
                        {% if mapa_seznamu.get(p, 'todo.nakupni_seznam_ostatni') == aktualni_seznam %}
                          {% set ns.items = dict(ns.items, **{p: ns.items.get(p, 0) + 1}) %}
                        {% endif %}
                      {% endfor %}
                    {% endif %}
                  {% endfor %} {{ ns.items }}
            # 캛i코t캩n칤 a op캩tovn칠 p콏id치n칤 (pro s캜칤t치n칤 polo쬰k)
            - if:
                - condition: template
                  value_template: "{{ seznam[aktualni_seznam]['items'] | length > 0 }}"
              then:
                - repeat:
                    for_each: "{{ seznam[aktualni_seznam]['items'] }}"
                    sequence:
                      - action: todo.remove_item
                        target:
                          entity_id: "{{ aktualni_seznam }}"
                        data:
                          item: "{{ repeat.item.summary }}"
            - repeat:
                for_each: "{{ vsechny_polozky | dictsort }}"
                sequence:
                  - action: todo.add_item
                    target:
                      entity_id: "{{ aktualni_seznam }}"
                    data:
                      item: >-
                        {% set n = repeat.item[0] %} {% set c = repeat.item[1] %} {%
                        if c > 1 %}{{ c }}x {{ n }}{% else %}{{ n }}{% endif %}

# 4. AUTOMATIZACE (칔klid)
automation:
  - alias: J칤deln칤캜ek - Vymazat dne코n칤 den
    description: "Ka쬯칳 den ve 21:00 vyresetuje j칤deln칤캜ek pro aktu치ln칤 den."
    triggers:
      - at: "21:00:00"
        trigger: time
    actions:
      - variables:
          dny_zkratky: [po, ut, st, ct, pa, so, ne]
          den: "{{ dny_zkratky[now().weekday()] }}"
          prefix: "{{ 't1' if now().isocalendar().week % 2 != 0 else 't2' }}"
      - target:
          entity_id:
            - input_select.menu_{{ prefix }}_{{ den }}_snidane
            - input_select.menu_{{ prefix }}_{{ den }}_obed
            - input_select.menu_{{ prefix }}_{{ den }}_svacina
            - input_select.menu_{{ prefix }}_{{ den }}_vecere
        data:
          option: "---"
        action: input_select.select_option
    mode: single
